### PR TITLE
New Architecture that helps sharing modules between projects. 

### PR DESCRIPTION
**Pull request by methodik**

### CODE REVIEW

**Comment by methodik** [comment]
@luliandro I'm getting a load of messages above telling me that the Travis CI has failed? What should I do about that?

**Comment by luliandro** [comment]
@methodik travis-ci runs "grunt" to compile .less files. If this command fails, then the build fails.

if you run "grunt" on your local machine you should be able see and fix errors. If I remember right you got rid of main.css, so maybe grunt is trying to find main.less and failing.

**Comment by luliandro** [comment]
actually just checked https://travis-ci.org/hevnly/asset-bazaar and it's passing

**Comment by methodik** [comment]
@luliandro OK, so are we OK to go ahead and merge the PR?

**Comment by luliandro** [comment]
I think so yes,

**Pull request merged**
